#!/bin/bash

set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

if [[ "${PROXY_IP:-X}" != "X" ]]; then
  : ${PROXY_USERNAME:?required if PROXY_IP set}
  : ${PROXY_PRIVATE_KEY:?required if PROXY_IP set}
  ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
  cd $ROOT

  mkdir -p proxy/ssh
  chmod 700 proxy/ssh
  echo "${PROXY_PRIVATE_KEY}" > proxy/ssh/private_key
  chmod 600 proxy/ssh/private_key

  header "Checking jumpbox available..."
  set +e
  until ssh ${PROXY_USERNAME}@${PROXY_IP} -i proxy/ssh/private_key \
      -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=60 \
      "whoami"
  do
    echo "Waiting until jumpbox/proxy available..."
  done
  set -e

  header "Starting socks5 proxy..."
  ssh ${PROXY_USERNAME}@${PROXY_IP} -i proxy/ssh/private_key -N -D 9999 &
  sleep 10

  echo BOSH_ALL_PROXY=socks5://localhost:9999
  export BOSH_ALL_PROXY=socks5://localhost:9999
fi

header "Checking bosh available..."
until bosh2 env; do
  echo "Waiting until bosh available..."
	sleep 60
done

if [[ -f git/tmp/vars.yml ]]; then
	cf_api_url=$(bosh2 int git/tmp/vars.yml --path /cf-api-url)
	if [[ "${cf_api_url:-X}" != "X" ]]; then
		header "Checking Cloud Foundry available..."
		until cf api $cf_api_url --skip-ssl-validation; do
		  echo "Waiting until Cloud Foundry available..."
		  sleep 60
		done
	fi
fi

echo
echo
